version: 1.0.{build}
image: Visual Studio 2015
configuration: Debug
platform: x64
before_build:
  - nuget restore
build:
  verbosity: minimal
test_script:
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\FunctionsTests.exe'
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\TestGetNum.exe'
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\TestParsed.exe'
  - '%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\TestReplace.exe'
